config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :todos do
    member do
      patch :complete
    end
  end

  root "todos#index" 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates_presence_of :title, :due_date 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
    before_action :set_todo, :only => [:show, :edit, :update, :destroy, :complete]
  def index
    @todos = Todo.all
  end
  def new
    @todo = Todo.new
  end
  def create
    @todo = Todo.new(todo_params)
    if @todo.save
      redirect_to todos_url
    else
      render :new
    end
  end
  def show
  end
  def update
    if @todo.update_attributes(todo_params)
      redirect_to todos_path(@todo)
    else
      render :edit
    end
  end
  def complete
    if @todo.completed == false
      @todo.update_attribute(:completed, true)
    else
      @todo.update_attribute(:completed, false)
    end
    redirect_to todos_path(@todo)
  end

  def destroy
    @todo.destroy
    redirect_to todos_url
  end
   
  private
  def set_todo
    @todo = Todo.find(params[:id])
  end
  def todo_params
    params.require(:todo).permit(:title, :due_date, :note, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<% if @todo.errors.present? %>
  <ul>
    <% @todo.errors.each do |error, message| %>
      <li> <%= "#{error.capitalize}  #{message}" %></li>
    <% end %>
  </ul>
<% end %>
<div class="form container">
  <%= form_for @todo do |f| %>
    <div class="form-group">
      <%= f.label :title, "Title" %>
      <%= f.text_field :title, class: "form-control" %>  
    </div>


  <div class="form-group">
    <%= f.label :due_date, "Due_date" %>
    <%= f.text_field :due_date, class: "form-control" %>
  </div>    

  <div class="form-group">
    <%= f.label :note, "Note" %>
    <%= f.text_area :note, class: "form-control" %>
  </div>

  <%= f.submit %>
</div>

<% end %>

app/views/todos/edit.html.erb
<%= render :partial => "form" %>

app/views/todos/index.html.erb
<div class="container">
  <div class="page-header">
    <h1>代辦事項
    <small>Therefore do not worry about tomorrow, for tomorrow will worry about itself.
    </small>
  </h1>
  </div>

  <table class="table table-striped table-condensed table-hover">
    <tr>
        <td>狀態</td>
        <td>事項</td>
        <td>到期日</td>
        <td>筆記</td>
        <td>編輯</td>
        <td>刪除</td>
    </tr>
    <% @todos.each do |todo| %>        
      <tr>
        <% if todo.completed %>
          <td>
            <%= link_to complete_todo_path(todo), method: :patch do %>
              <span class="glyphicon glyphicon-check"></span>
            <% end %>
          </td>
        <% else %>
          <td>
            <%= link_to complete_todo_path(todo), method: :patch do %>
              <span class="glyphicon glyphicon-unchecked"></span>
            <% end %>
          </td>
        <% end %>
        <td><%= todo.title %></td>
        <td><%= todo.due_date %></td>

        <td><%= todo.note %></td>

        <td>
          <%= link_to edit_todo_path(todo) do %>
            <span class="glyphicon glyphicon-edit"></span>
          <% end %>    
        </td>
        
        <% if Time.now.to_date <= todo.due_date %>
          <td>
            <%= link_to todo_path(todo), method: :delete, data:{ confirm: "Are you sure?" } do %>
              <span class="glyphicon glyphicon-trash"></span>
            <% end %>
          </td>
        <% else %>
          <td>expired</td>
        <% end %>

      </tr>  
    <% end %>
  </table>


  <div style="margin-top: 100px" class="col-sm-offset-2 col-sm-8">
    <%= form_for @todos.build do |f| %>
      <div class="form-group">
        <%= f.label :title, "Title" %>
        <%= f.text_field :title, class: "form-control" %>  
      </div>
      <div class="form-group">
        <%= f.label :due_date, "Due_date" %>
        <%= f.text_field :due_date, class: "form-control" %>
      </div>    
      <div class="form-group">
        <%= f.label :note, "Note" %>
        <%= f.text_area :note, class: "form-control" %>
      </div>
      <%= f.submit %>
    <% end %>
  </div>  
</div>

app/views/todos/new.html.erb
<%= render :partial => "form" %>

app/views/todos/show.html.erb
<div class="container">
  <h1>
    <%= @todo.title %>
    <small>
      <%= @todo.due_date %>
    </small>
  </h1>
  <p>
    Note: <%= simple_format(@todo.note) %>
  </p>
  <%= link_to 'Back to index', todos_path %>
</div>